name: CI

on:
  push:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Install Debian package build data
        run: sudo apt-get update && sudo apt-get install --yes nmap-common
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Run tests
        run: cargo test --locked
      - name: Run Clippy
        run: cargo clippy --all-targets --locked -- -D warnings
      - name: Build Debian package
        run: ./scripts/build-deb.sh
      - uses: actions/upload-artifact@v4
        with:
          name: netmapper-dpkg
          path: dist/netmapper.dpkg